### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by ahmadJS487** [dickymuliafiqri/onecak#1]
https://onecak.azurewebsites.net/?shuffle=1

Saya mempunyai masalah ketika `response.posts[0].url ` tidak di akses atau di buka maka `response.posts[0].src` tidak muncul image dan error 403 Forbidden

Tapi kadang juga  403 Forbidden, walaukun url sudah di buka di newtab

![image](https://user-images.githubusercontent.com/92171013/137262348-c6664970-a353-477f-91d7-b0d57432c428.png)

**Comment by dickymuliafiqri** [comment]
Memang dari situs 1cak, entah dia pake cookies, atau semacamnya.

Yang jelas kalo mau ambil gambar dari src harus buka url dulu untuk dapat aksesnya.


Untuk masalah paragraf 2, coba buka di new window atau hapus cookies.
